# Generated by Django 4.2.1 on 2024-03-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['-time_create'], name='restaurant__time_cr_b4097a_idx'),
        ),
    ]
