# Generated by Django 4.2.1 on 2024-03-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='content',
            new_name='review',
        ),

        migrations.AddField(
            model_name='restaurant',
            name='author',
            field=models.TextField(blank=True),
        ),
    ]
