# Generated by Django 4.2.1 on 2024-03-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_content_restaurant_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='time_update',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dish',
            field=models.CharField(default='rfrfrfrfrfrf', max_length=100),
        ),
    ]
