# Generated by Django 4.2.1 on 2024-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_restaurant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='title',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dish',
            field=models.CharField(max_length=100),
        ),
    ]
