# Generated by Django 4.2.1 on 2024-03-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_restaurant_title_alter_restaurant_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image_post/'),
        ),
    ]
