# Generated by Django 4.2.1 on 2024-03-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_category_restaurant_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.category'),
        ),
    ]
