# Generated by Django 4.2.1 on 2024-03-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_tagpost_alter_restaurant_cat_restaurant_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='restaurant.contact'),
        ),
    ]
